# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studioflow-production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: studioflowregistry.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_4951A98654B14C4A83A485081A220127 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_6568E30121964372A90028E01D41495A }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./studioflow/server
          push: true
          tags: studioflowregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_4951A98654B14C4A83A485081A220127 }}/studioflow-production:${{ github.sha }}
          file: ./studioflow/server/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_293F1C2CD60C487094DB9459F671391A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9065C955386C40B8B03B31236098658C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1BCB99376F4F4B2C9614B7AEB22A6005 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'studioflow-production'
          slot-name: 'Production'
          images: 'studioflowregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_4951A98654B14C4A83A485081A220127 }}/studioflow-production:${{ github.sha }}'
